# Generated by Django 2.2.5 on 2021-06-24 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_id', models.CharField(max_length=64, unique=True, verbose_name='商品id')),
                ('good_name', models.CharField(max_length=64, verbose_name='商品名')),
                ('good_description', models.CharField(max_length=64, verbose_name='商品描述')),
                ('good_img', models.TextField(verbose_name='商品图片')),
                ('ingredient_img_url', models.TextField(verbose_name='调料包图片url')),
                ('good_sale_status', models.BooleanField(default=True, verbose_name='是否上架')),
            ],
            options={
                'verbose_name': '11-商品表',
                'verbose_name_plural': '11-商品表',
            },
        ),
        migrations.CreateModel(
            name='ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salt', models.FloatField(verbose_name='盐量')),
                ('alc', models.FloatField(verbose_name='料酒量')),
                ('thinsoy', models.FloatField(verbose_name='生抽量')),
                ('vinegar', models.FloatField(verbose_name='醋量')),
                ('thicksoy', models.FloatField(verbose_name='老抽量')),
                ('sugar', models.FloatField(verbose_name='糖量')),
                ('pepper', models.FloatField(verbose_name='花椒量')),
                ('aginomoto', models.FloatField(verbose_name='味精量')),
            ],
            options={
                'verbose_name': '21-调料表',
                'verbose_name_plural': '21-调料表',
            },
        ),
        migrations.CreateModel(
            name='machine_address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16, verbose_name='售货机标题')),
                ('province', models.CharField(max_length=16, verbose_name='售货机省份')),
                ('city', models.CharField(max_length=16, verbose_name='售货机城市')),
                ('district', models.CharField(max_length=16, verbose_name='售货机区')),
                ('detailed_address', models.CharField(max_length=128, verbose_name='详细地址')),
                ('machine_id', models.CharField(max_length=16, verbose_name='售货机号')),
                ('available_time', models.CharField(max_length=16, verbose_name='营业时间')),
                ('phone_number', models.CharField(max_length=32, verbose_name='联系电话')),
                ('longitude', models.CharField(max_length=32, verbose_name='经度')),
                ('latitude', models.CharField(max_length=32, verbose_name='纬度')),
            ],
            options={
                'verbose_name': '14-机器表',
                'verbose_name_plural': '14-机器表',
            },
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_uid', models.CharField(max_length=128, verbose_name='唯一订单号')),
                ('order_price', models.FloatField(verbose_name='订单金额')),
                ('order_status', models.IntegerField(choices=[(1, '未支付'), (2, '已支付，待取货'), (3, '已出货'), (4, '已取消'), (5, '已退款'), (6, '异常订单')], verbose_name='订单状态')),
                ('order_pickup_machine_id', models.CharField(max_length=32, verbose_name='取货机器号')),
                ('order_pickup_machine_address', models.CharField(max_length=256, verbose_name='取货机详细地址')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='订单创建时间')),
                ('completed_time', models.DateTimeField(null=True, verbose_name='订单完成时间')),
                ('paid_time', models.DateTimeField(auto_now_add=True, verbose_name='支付完成时间')),
                ('qr_path', models.TextField(verbose_name='二维码图片存储地址')),
                ('order_note', models.CharField(max_length=32, null=True, verbose_name='订单备注')),
                ('phone_num', models.CharField(max_length=16, verbose_name='手机号')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.User', verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '15-订单表',
                'verbose_name_plural': '15-订单表',
            },
        ),
        migrations.CreateModel(
            name='order_good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_orderAmount', models.IntegerField(verbose_name='下单数量')),
                ('alt_salty', models.IntegerField(verbose_name='选择咸度')),
                ('alt_spicy', models.IntegerField(verbose_name='选择辣度')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='goods.good', verbose_name='下单菜品')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='goods.ingredients', verbose_name='下单菜品的调料')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_good', to='goods.order', verbose_name='对应订单')),
            ],
        ),
        migrations.CreateModel(
            name='good_attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_id', models.IntegerField(null=True, verbose_name='属性id')),
                ('rec_salt', models.IntegerField(verbose_name='推荐商品咸度')),
                ('rec_amount', models.IntegerField(verbose_name='推荐商品分量')),
                ('goods_type1', models.IntegerField(choices=[(1, '川'), (2, '鲁'), (3, '粤'), (4, '其他')], verbose_name='菜系')),
                ('goods_type2', models.IntegerField(choices=[(1, '平底锅'), (2, '汤锅'), (3, '微波炉'), (4, '电饭煲')], verbose_name='锅具')),
                ('amount', models.IntegerField(verbose_name='商品库存')),
                ('price', models.FloatField(max_length=64, verbose_name='价格')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goodattr', to='goods.good', verbose_name='对应商品')),
                ('ingredient', models.ForeignKey(on_delete=False, to='goods.ingredients', unique=True, verbose_name='调料内容')),
            ],
            options={
                'verbose_name': '13-商品属性表',
                'verbose_name_plural': '13-商品属性表',
            },
        ),
    ]
